-- migrate:up

-- Sets up a trigger for the given table to automatically set a column called
-- `updated_at` whenever the row is modified (unless `updated_at` was included
-- in the modified columns)
--
-- # Example
--
-- ```sql
-- CREATE TABLE users (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
--
-- SELECT diesel_manage_updated_at('users');
-- ```
CREATE OR REPLACE FUNCTION updated_at(_tbl regclass) RETURNS VOID AS $$
BEGIN
    EXECUTE format('CREATE TRIGGER set_updated_at BEFORE UPDATE ON %s
                    FOR EACH ROW EXECUTE PROCEDURE set_updated_at()', _tbl);
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
    IF (
        NEW IS DISTINCT FROM OLD AND
        NEW.updated_at IS NOT DISTINCT FROM OLD.updated_at
    ) THEN
        NEW.updated_at := current_timestamp;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- These roles are only created in development. In production they will
-- have already been created by the infrastructure as code and have unguessable passwords.

DO $$
BEGIN
   IF NOT EXISTS (
      SELECT FROM pg_catalog.pg_roles
      WHERE  rolname = 'typednotes_application') THEN

      CREATE ROLE typednotes_application LOGIN PASSWORD 'testpassword';
   END IF;
END
$$;

DO $$
BEGIN
   IF NOT EXISTS (
      SELECT FROM pg_catalog.pg_roles
      WHERE  rolname = 'typednotes_readonly') THEN

      CREATE ROLE typednotes_readonly LOGIN PASSWORD 'testpassword';
   END IF;
END
$$;

-- Now for authentication

CREATE TABLE users (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    openid_sub VARCHAR NOT NULL UNIQUE,
    email VARCHAR NOT NULL UNIQUE,
    first_name VARCHAR,
    last_name VARCHAR,
    system_admin BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Give access to the application user, the application user has no access to 
-- the sessions table and therefore cannot fake a login.
GRANT SELECT, UPDATE, INSERT ON users TO typednotes_application;
GRANT USAGE, SELECT ON users_id_seq TO typednotes_application;

-- Give access to the readonly user
GRANT SELECT ON users, users_id_seq TO typednotes_readonly;

-- Manage the updated_at column
SELECT updated_at('users');


-- The very simplest RBAC implementation, the roles get added to the team_users table
-- as users are added to an org.

CREATE TYPE role AS ENUM (
    'Administrator', 
    'Collaborator'
);
COMMENT ON TYPE role IS 'Users have roles, they can be managers or administrators etc.';

CREATE TYPE visibility AS ENUM (
    'Company', 
    'Team', 
    'Private'
);
COMMENT ON TYPE visibility IS 'For some data the user can select the visibility';

CREATE TYPE permission AS ENUM (
    -- The ManageTeam permission gives the user thee ability to invite team members, 
    -- delete team members and change the team name
    'ManageTeam'
);
COMMENT ON TYPE permission IS 'A permission gives the user the ability to do something. i.e. Manage users.';

CREATE TABLE roles_permissions (
    role role NOT NULL,
    permission permission NOT NULL,

    PRIMARY KEY (role, permission)
);
COMMENT ON TABLE roles_permissions IS 'Maps roles to permissions. i.e. a role can have multiple permissions.';

INSERT INTO roles_permissions VALUES('Administrator', 'ManageTeam');


-- Give access to the application user.
GRANT SELECT ON roles_permissions TO bionic_application;

-- Give access to the readonly user
GRANT SELECT ON roles_permissions TO bionic_readonly;

-- Teams
CREATE TABLE teams (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    name VARCHAR,
    created_by_user_id INT NOT NULL
);

COMMENT ON TABLE teams IS 'An team is created for everyone that signs up. It could also have been called teams.';
COMMENT ON COLUMN teams.name IS 'The name of the team i.e. Microsoft or perhaps a persons name';
COMMENT ON COLUMN teams.created_by_user_id IS 'The action committed. i.e. deleting a secret etc.';

CREATE TABLE team_users (
    user_id INT NOT NULL, 
    team_id INT NOT NULL,
    roles role ARRAY NOT NULL,
    PRIMARY KEY (user_id, team_id)
);

COMMENT ON TABLE team_users IS 'A User can belong to multiple teams (teams).';
COMMENT ON COLUMN team_users.roles IS 'The RBAC privelages the user has for this team.';

CREATE TABLE invitations (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    team_id INT NOT NULL, 
    email VARCHAR NOT NULL,
    first_name VARCHAR NOT NULL,
    last_name VARCHAR NOT NULL,
    roles role ARRAY NOT NULL,
    invitation_selector VARCHAR NOT NULL,
    invitation_verifier_hash VARCHAR NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_team
        FOREIGN KEY(team_id) 
        REFERENCES teams(id)
);

COMMENT ON TABLE invitations IS 'Invitations are generated so users can join teams (teams)';
COMMENT ON COLUMN invitations.team_id IS 'The team that the user will join if they acccept the invite';
COMMENT ON COLUMN invitations.roles IS 'The RBAC privelages the user will receive on joining the team (team).';
COMMENT ON COLUMN invitations.invitation_selector IS 'To avoid timing attacks the inviation secret is split into a lookup then a verfication.';
COMMENT ON COLUMN invitations.email IS 'After we lookup the invite we check that the hash is correct';

-- Give access to the application user, the application user has no access to 
-- The sessions table and therefore cannot fake a login.
GRANT SELECT, INSERT ON team_users TO bionic_application;
GRANT SELECT, INSERT, UPDATE ON teams TO bionic_application;
GRANT SELECT, INSERT, DELETE ON invitations TO bionic_application;
GRANT USAGE, SELECT ON invitations_id_seq, teams_id_seq TO bionic_application;

-- Give access to the readonly user
GRANT SELECT ON invitations, teams, team_users TO bionic_readonly;
GRANT SELECT ON invitations_id_seq, teams_id_seq TO bionic_readonly;


-- Lock down the database

-- Helper functions for tenancy isolation 
CREATE FUNCTION current_app_user() RETURNS INTEGER AS 
$$ 
    SELECT
        current_setting(
            'row_level_security.user_id',
            false
        )::integer 
$$ LANGUAGE SQL;
COMMENT ON FUNCTION current_app_user IS 
    'These needs to be set by the application before accessing the database.';

CREATE FUNCTION is_app_user_sys_admin() RETURNS BOOLEAN AS 
$$ 
    SELECT
        system_admin
    FROM
        users
    WHERE
        id = current_app_user()
    LIMIT 1
$$ LANGUAGE SQL;
COMMENT ON FUNCTION is_app_user_sys_admin IS 
    'Is the current user a sys admin?';

CREATE FUNCTION get_teams_for_app_user() RETURNS SETOF INTEGER AS 
$$
DECLARE
    is_sys_admin BOOLEAN;
BEGIN
    is_sys_admin := is_app_user_sys_admin();

    IF is_sys_admin THEN
        RETURN QUERY SELECT
            team_id
        FROM
            team_users;
    ELSE
        RETURN QUERY SELECT
            team_id
        FROM
            team_users
        WHERE
            user_id = current_app_user();
    END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
COMMENT ON FUNCTION get_teams_for_app_user IS 
    'All the teams a user has been invited to or all teams for sys admin.';

CREATE FUNCTION get_teams_app_user_created() RETURNS setof integer AS 
$$ 
    SELECT
        id
    FROM
        teams
    WHERE
        created_by_user_id = current_app_user()
$$ LANGUAGE SQL SECURITY DEFINER;
COMMENT ON FUNCTION get_teams_app_user_created IS 
    'All the teams a user created.';

CREATE FUNCTION get_users_for_app_user() RETURNS setof integer AS 
$$ 
DECLARE
    is_sys_admin BOOLEAN;
BEGIN
    is_sys_admin := is_app_user_sys_admin();

    IF is_sys_admin THEN
        RETURN QUERY SELECT
            user_id
        FROM
            team_users;
    ELSE
        RETURN QUERY 
            SELECT
                user_id
            FROM
                team_users
            WHERE
                team_id IN (SELECT get_teams_for_app_user());
    END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
COMMENT ON FUNCTION get_users_for_app_user IS 
    'All the users from all the teams this user has been invited to.';


-- migrate:down

DROP TABLE users;

DROP TABLE roles_permissions;
DROP TYPE role;
DROP TYPE permission;
DROP TYPE visibility;

DROP TABLE team_users;
DROP TABLE invitations;
DROP TABLE teams;

DROP FUNCTION current_app_user;
DROP FUNCTION get_teams_for_app_user;
DROP FUNCTION get_users_for_app_user;
DROP FUNCTION get_teams_app_user_created;
DROP FUNCTION is_app_user_sys_admin;
