-- migrate:up

-- CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE spaces (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id INT NOT NULL,
    parent_id INT, -- May not have a parent (the root space)
    visibility visibility NOT NULL,
    name VARCHAR NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_group FOREIGN KEY(group_id)
        REFERENCES groups(id) ON DELETE CASCADE,
    
    CONSTRAINT fk_parent FOREIGN KEY(parent_id)
        REFERENCES spaces(id) ON DELETE CASCADE
);

CREATE TABLE notes (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    group_id INT NOT NULL,
    space_id INT, -- May not have a space (the root space of the group)
    visibility visibility NOT NULL,
    name VARCHAR NOT NULL,
    type VARCHAR NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_group FOREIGN KEY(group_id)
        REFERENCES groups(id) ON DELETE CASCADE
);

-- Give access to the application user.
GRANT SELECT, INSERT, UPDATE, DELETE ON spaces, notes TO typednotes_application;
GRANT SELECT ON spaces, notes TO typednotes_application;

-- Give access to the readonly user
GRANT SELECT, INSERT, UPDATE, DELETE ON spaces, notes TO typednotes_readonly;
GRANT SELECT ON spaces, notes TO typednotes_readonly;

-- migrate:down

DROP TABLE spaces;
DROP TABLE notes;
