-- migrate:up

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE spaces (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    group_id INT NOT NULL,
    parent_id INT, -- May not have a parent (the root space)
    visibility visibility NOT NULL,
    name VARCHAR NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_group FOREIGN KEY(group_id)
        REFERENCES groups(id) ON DELETE CASCADE,
    
    CONSTRAINT fk_parent FOREIGN KEY(parent_id)
        REFERENCES parent(id) ON DELETE CASCADE,
);

CREATE TABLE notes (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    group_id INT NOT NULL,
    space_id INT, -- May not have a space (the root space of the group)
    visibility visibility NOT NULL,
    name VARCHAR NOT NULL,
    type VARCHAR NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_group FOREIGN KEY(group_id)
        REFERENCES groups(id) ON DELETE CASCADE,

    CONSTRAINT fk_model FOREIGN KEY(embeddings_model_id)
        REFERENCES models(id) ON DELETE CASCADE
);

CREATE TABLE chunks (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    document_id INT NOT NULL, 
    text VARCHAR NOT NULL, 
    page_number INT NOT NULL, 
    embeddings vector, 
    processed BOOL NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_document FOREIGN KEY(document_id)
        REFERENCES documents(id) ON DELETE CASCADE
);

-- Give access to the application user.
GRANT SELECT, INSERT, UPDATE, DELETE ON documents, chunks, datasets TO bionic_application;
GRANT USAGE, SELECT ON documents_id_seq, chunks_id_seq, datasets_id_seq TO bionic_application;

-- Give access to the readonly user
GRANT SELECT, INSERT, UPDATE, DELETE ON documents, chunks, datasets TO bionic_readonly;
GRANT USAGE, SELECT ON documents_id_seq, chunks_id_seq, datasets_id_seq TO bionic_readonly;

-- migrate:down

DROP TABLE chunks;
DROP TABLE documents;
DROP TABLE datasets;
DROP TYPE chunking_strategy;