-- migrate:up

-- Organizations are where billing and admin happens, organizations are unstructured entities (no hierarchy)
CREATE TABLE organizations (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR
);

-- Groups are ways to organize users in an organization
CREATE TABLE groups (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INT NOT NULL,
    name VARCHAR,
    created_by_user_id INT NOT NULL,

    CONSTRAINT fk_organization FOREIGN KEY(organization_id)
        REFERENCES organizations(id) ON DELETE CASCADE
);

COMMENT ON TABLE groups IS 'A group is created for everyone that signs up.';
COMMENT ON COLUMN groups.name IS 'The name of the group';
COMMENT ON COLUMN groups.created_by_user_id IS 'Created by';

CREATE TABLE group_users (
    user_id INT NOT NULL, 
    group_id INT NOT NULL,
    roles role ARRAY NOT NULL,
    PRIMARY KEY (user_id, group_id),

    CONSTRAINT fk_user FOREIGN KEY(user_id)
        REFERENCES users(id) ON DELETE CASCADE,
    
    CONSTRAINT fk_group FOREIGN KEY(group_id)
        REFERENCES groups(id) ON DELETE CASCADE
);

COMMENT ON TABLE group_users IS 'A User can belong to multiple groups.';
COMMENT ON COLUMN group_users.roles IS 'The RBAC privelages the user has for this group.';

CREATE TABLE invitations (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    group_id INT NOT NULL, 
    email VARCHAR NOT NULL,
    first_name VARCHAR NOT NULL,
    last_name VARCHAR NOT NULL,
    roles role ARRAY NOT NULL,
    invitation_selector VARCHAR NOT NULL,
    invitation_verifier_hash VARCHAR NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_group
        FOREIGN KEY(group_id) 
        REFERENCES groups(id)
);

COMMENT ON TABLE invitations IS 'Invitations are generated so users can join groups';
COMMENT ON COLUMN invitations.group_id IS 'The group that the user will join if they acccept the invite';
COMMENT ON COLUMN invitations.roles IS 'The RBAC privelages the user will receive on joining the group.';
COMMENT ON COLUMN invitations.invitation_selector IS 'To avoid timing attacks the inviation secret is split into a lookup then a verfication.';
COMMENT ON COLUMN invitations.email IS 'After we lookup the invite we check that the hash is correct';

-- Give access to the application user, the application user has no access to 
-- The sessions table and therefore cannot fake a login.
GRANT SELECT, INSERT ON group_users TO typednotes_application;
GRANT SELECT, INSERT, UPDATE ON groups TO typednotes_application;
GRANT SELECT, INSERT, DELETE ON invitations TO typednotes_application;
GRANT USAGE, SELECT ON invitations_id_seq, groups_id_seq TO typednotes_application;

-- Give access to the readonly user
GRANT SELECT ON invitations, groups, group_users TO typednotes_readonly;
GRANT SELECT ON invitations_id_seq, groups_id_seq TO typednotes_readonly;

-- migrate:down

DROP TABLE group_users;
DROP TABLE invitations;
DROP TABLE groups;
